### ISSUE TITLE
Error on running scans with TOR proxy

### ISSUE THREAD

**Issue by gchib297** [smicallef/spiderfoot#700]
Error occurs when spiderfoot is configured to use TOR as proxy. Scans run successfully without TOR.

**Version info**
`Spiderfoot: v3.2-DEV`
`Tor: tor-win32-0.4.3.6`
`Python: 3.7.4`

**Steps to reproduce:**

1. Configured TOR proxy in spiderfoot:
![spf01](https://user-images.githubusercontent.com/11896766/90229930-5a220280-de36-11ea-916f-2cbd10d20aa6.PNG)

2. Scans fail with below error:
```
Unrecoverable error in the server.
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\Gaurav\VAPT\immuniweb\osint\spiderfoot\sfwebui.py", line 599, in scaninfo
    pageid="SCANLIST")
  File "C:\Python37\lib\site-packages\mako\template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python37\lib\site-packages\mako\runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "C:\Python37\lib\site-packages\mako\runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python37\lib\site-packages\mako\runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "dyn_scaninfo_tmpl", line 44, in render_body
UnboundLocalError: local variable 'statusy' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 604, in run
    self.respond(pi)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 653, in respond
    self.handle_error()
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 766, in handle_error
    self.error_response()
  File "D:\Gaurav\VAPT\immuniweb\osint\spiderfoot\sfwebui.py", line 104, in error_page
    cherrypy.response.body = '<html><body>Error</body></html>'
  File "C:\Python37\lib\site-packages\cherrypy\__init__.py", line 231, in __setattr__
    setattr(child, name, value)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 792, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.
```

**Comment by bcoles** [comment]
Hi. Thanks for the report. It's possible that this is racey. It is mostly likely only a UI error.

A couple questions which will help us narrow down the cause:

* Does the scan start run successfully, regardless of the UI error? ie, can you navigate to the scan list page and see the scan in the scan list?
* Does the scan complete?

**Comment by bcoles** [comment]
The following diff should fix the UI, but won't fix the underlying issue which is related to TOR.

```
diff --git a/dyn/scaninfo.tmpl b/dyn/scaninfo.tmpl
index bd8b22e..8851f6b 100644
--- a/dyn/scaninfo.tmpl
+++ b/dyn/scaninfo.tmpl
@@ -7,7 +7,7 @@
     statusy = "alert-warning"
   elif status == "RUNNING" or status == "STARTED" or status == "STARTING" or status == "INITIALIZING":
     statusy = "alert-info"
-  elif status == "FAILED":
+  elif status == "ERROR-FAILED":
     statusy = "alert-danger"
   end
 %>
```

**Comment by gchib297** [comment]
Hi @bcoles ,
Thanks for the response. I've tried the diff changes, but the UI error still occurs on scans.

> * Does the scan start run successfully, regardless of the UI error? ie, can you navigate to the scan list page and see the scan in the scan list?

Yes. It is also able to fetch results using TOR.

> * Does the scan complete?

Yes, scans complete successfully.

**Comment by bcoles** [comment]
> 
> 
> Hi @bcoles ,
> Thanks for the response. I've tried the diff changes, but the UI error still occurs on scans.
> 
> > * Does the scan start run successfully, regardless of the UI error? ie, can you navigate to the scan list page and see the scan in the scan list?
> 
> Yes. It is also able to fetch results using TOR.
> 
> > * Does the scan complete?
> 
> Yes, scans complete successfully.

Thanks. Interesting.

You can try applying the patch above which might help. Or wait until Steve merges my PR into the master branch - probably some time later today.

**Comment by bcoles** [comment]
The UI error should now be fixed on `master` branch.

I tried to reproduce whatever the underlying issue is with TOR, but wasn't able to reproduce on Linux.

If you encounter the error again, or have any relevant logs in the scan logs, please post them.

**Comment by gchib297** [comment]
Thanks @bcoles, issue resolved. All the scans run fine now.
